[build]
  publish = "public"
  command = "mkdir -p public && echo '<html><body>Qexo with Supabase</body></html>' > public/index.html"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/qexo/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/qexo/:splat"
  status = 200

[functions]
  directory = "netlify/functions"

# 增加超时时间，Qexo 可能需要更长时间
[functions.qexo]
  timeout = 30
