[build]
  publish = "staticfiles"
  command = "pip install -r requirements.txt"

[[redirects]]
  from = "/*"
  to = "/api/index.py"
  status = 200
  force = false
  conditions = {RequestPath = ["!^/static/", "!^/_next/static/", "!^/admin/static/", "!^/favicon.ico", "!^/robots.txt"]}

[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/*"
  to = "/api/index.py"
  status = 200
  force = false
  conditions = {RequestPath = ["!^/static/"]}
