[build]
  publish = "public"
  command = "mkdir -p public && echo '<html><body>Qexo Backend</body></html>' > public/index.html"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/qexo/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/qexo/:splat"
  status = 200

[functions]
  directory = "netlify/functions"

[dev]
  command = "python manage.py runserver"
  targetPort = 5000
  publish = "public"
