[build]
  publish = "staticfiles"
  command = "pip install -r requirements.txt && mkdir -p staticfiles"

[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/api/index.py"
  status = 200
