[build]
  publish = "staticfiles"  # 这是 Django collectstatic 命令输出的目录，也可能是 "public"
  command = "pip install -r requirements.txt && python manage.py collectstatic --noinput"

[[redirects]]
  from = "/*"
  to = "/api/index.py"
  status = 200
  force = false
  conditions = {RequestPath = ["!^/static/", "!^/_next/static/", "!^/admin/static/", "!^/favicon.ico", "!^/robots.txt"]}

[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/*"
  to = "/api/index.py"
  status = 200
  force = false
  conditions = {RequestPath = ["!^/static/"]}